
import React from 'react';

export const Disclaimer: React.FC = () => {
    return (
        <div className="mt-8 p-6 bg-yellow-50 dark:bg-yellow-900/20 border-l-4 border-yellow-400 text-yellow-800 dark:text-yellow-200 rounded-r-lg">
            <h3 className="font-bold text-lg mb-2">Important Disclaimer & Instructions</h3>
            <div className="text-sm space-y-2">
                <p>
                    <strong>For Educational & Testing Purposes Only:</strong> The numbers generated by this tool are completely random and algorithmically created. They are not real credit card numbers, have no value, and cannot be used for any transactions.
                </p>
                <p>
                    <strong>Legal Warning:</strong> Attempting to use these numbers for fraudulent purposes is illegal. This tool is intended for developers and testers to populate user interfaces with placeholder data. We do not condone or support any illegal activities.
                </p>
                <p>
                    <strong>For Real Integration Testing:</strong> When testing integrations with payment processors (like Stripe, PayPal, Braintree, etc.), always use the official test card numbers provided directly in their documentation. Using those numbers ensures you are testing against their sandboxed systems correctly.
                </p>
                <p>
                    <strong>No Data Logging:</strong> All generation happens in your browser. No generated data is ever saved, logged, or sent to a server. Your session is private and secure.
                </p>
            </div>
        </div>
    );
};
